### ISSUE TITLE
Options should be merged with the defaults but they replace it completely

### ISSUE THREAD

**Issue by rodush** [prateekbh/preact-cli-sw-precache#1]
With this plugin it is not possible to really modify/overwrite a specific option of the sw-precache-webpack-plugin.

Proposal: 
instead of 
```
plugin.options = swPrecacheOptions;
```
do
```
Object.assign(plugin.options, swPrecacheOptions);
```
Or even better, use lodash.mergeDeep(), but not sure if that granularity is needed.

**Comment by prateekbh** [comment]
SGTM, feel free to send a PR or I can do it in a few days for u
